--[[
    ===============================
    DO NOT EDIT THIS FILE DIRECTLY!
    ===============================
    Unless it is an emergency hot fix, clone github.com/C-C-Minetest-Server/twi_atlatc_env
    and edit the files within STN_v3/src. Run make within STN_v3/ and copy
    env_setup.lua onto the server.
]]
--[[
    Station Track System, Version 3: 1F616EMO@twi
    Copyright (C) 2026  1F616EMO

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
]]

local is_loading = true -- luacheck: ignore
